import { SidebarProvider } from '@/components/ui/sidebar'
import type { Metadata } from 'next'
import DashboardHeader, {
  BreadCrumb,
} from './(components)/Dashboard/DashboardHeader'
import DashboardSidebar from './(components)/Dashboard/DashboardSideBar'

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
}

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SidebarProvider>
      <div className="flex h-screen w-full overflow-hidden">
        <DashboardSidebar />
        <div className="flex w-full flex-1 flex-col overflow-hidden">
          <DashboardHeader />
          <main className="bg-secondary/10 w-full flex-1 overflow-y-auto p-6">
            <BreadCrumb />
            <div className="pt-4">{children}</div>
          </main>
        </div>
      </div>
    </SidebarProvider>
  )
}
