import { SidebarProvider } from '@/components/ui/sidebar'
import type { Metadata } from 'next'
import DashboardHeader from './(components)/Dashboard/DashboardHeader'
import DashboardSidebar from './(components)/Dashboard/DashboardSideBar'
import { Folder, Home, Settings } from 'lucide-react'
import BreadCrumb from './(components)/Dashboard/BreadCrumb'

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
}

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const menuItems = [
    {
      icon: <Home className="h-5 w-5" />,
      label: 'Overview',
      href: '/dashboard',
      isActive: false,
    },
    {
      icon: <Folder className="h-5 w-5" />,
      label: 'Events',
      href: '/dashboard/events',
      isActive: false,
    },
    {
      icon: <Settings className="h-5 w-5" />,
      label: 'Settings',
      href: '/dashboard/settings',
      isActive: false,
    },
  ]

  return (
    <SidebarProvider>
      <div className="flex h-screen w-full overflow-hidden">
        <DashboardSidebar menuItems={menuItems} />
        <div className="flex w-full flex-1 flex-col overflow-hidden">
          <DashboardHeader />
          <main className="bg-secondary/10 w-full flex-1 overflow-y-auto p-6">
            <BreadCrumb />
            <div className="pt-4">{children}</div>
          </main>
        </div>
      </div>
    </SidebarProvider>
  )
}
